language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - "14"
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  edge: true,
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  commit_message: "Deploy Release"
  on:
    branch: master
